import type {
  Db,
  Deadline,
  Milestone,
  Note,
  Paper,
  Project,
  ProjectActivity,
  ReviewJob,
  Task,
} from '@/lib/types';

// Seed data captured from a desktop survey on 2026-09-25.
// No invented deadlines or review jobs — user fills in real dates.
const NOW = '2026-09-25T09:00:00+09:00';

const projects: Project[] = [
  {
    id: 'p-realty-chart',
    slug: 'realty-chart',
    name: '동네시세 (realty-chart)',
    group: 'app',
    subgroup: '서비스',
    status: 'active',
    summary: '동네 단위 실거래가 시세 서비스',
    nextAction: '광역시 확장',
    links: [
      { label: '운영 대시보드', url: 'Work/realty-chart/tools/ops-dash/launch.bat', kind: 'local' },
      { label: 'GitHub', url: 'https://github.com/kkd2718/realty_view', kind: 'repo' },
    ],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\realty-chart'],
    pinned: true,
    sort: 0,
    color: 'cyan',
    updatedAt: NOW,
  },
  {
    id: 'p-trading-system',
    slug: 'trading-system',
    name: 'trading-system',
    group: 'app',
    subgroup: '재테크',
    status: 'active',
    summary: 'v3.6, GCloud VM에서 paper trading 중',
    nextAction: null,
    links: [
      { label: '계좌 대시보드', url: 'http://localhost:8899', kind: 'local' },
      { label: 'GitHub', url: 'https://github.com/kkd2718/trading-system', kind: 'repo' },
    ],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\trading-system'],
    pinned: true,
    sort: 0,
    color: 'amber',
    updatedAt: NOW,
  },
  {
    id: 'p-carenote',
    slug: 'carenote',
    name: 'CareNote (aesthetics-tracker)',
    group: 'app',
    subgroup: '개인',
    status: 'active',
    summary: '민감 정보 포함, localhost 전용',
    nextAction: null,
    links: [{ label: '대시보드', url: 'http://localhost:3010/people', kind: 'local' }],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\aesthetics\\aesthetics-tracker'],
    pinned: false,
    sort: 0,
    color: 'rose',
    updatedAt: NOW,
  },
  {
    id: 'p-amgi',
    slug: 'amgi',
    name: 'Amgi',
    group: 'app',
    subgroup: '공부',
    status: 'active',
    summary: 'Neon DB 소진, 10-01 리셋 후 일괄 ingest',
    nextAction: '10-01 리셋 후 일괄 ingest',
    links: [{ label: 'GitHub', url: 'https://github.com/kkd2718/amgi', kind: 'repo' }],
    paths: ['/home/kkd2718/projects/amgi'],
    pinned: false,
    sort: 1,
    color: 'violet',
    updatedAt: NOW,
  },
  {
    id: 'p-flow-sorter',
    slug: 'flow-sorter',
    name: 'flow-sorter (trAIcer)',
    group: 'app',
    subgroup: '사업',
    status: 'active',
    summary: 'trAIcer 사업용 워크플로 분류기',
    nextAction: '실증: 쉬는 날 하루 출근해서 실제처럼 사용 → 버그 확인',
    links: [{ label: 'GitHub', url: 'https://github.com/trAIcer-corp/flow-sorter', kind: 'repo' }],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\traicer-corp\\flow-sorter'],
    pinned: true,
    sort: 0,
    color: 'blue',
    updatedAt: NOW,
  },
  {
    id: 'p-personal-dashboard',
    slug: 'personal-dashboard',
    name: 'personal-dashboard',
    group: 'app',
    subgroup: '사업',
    status: 'active',
    summary: '이 앱. Command Center.',
    nextAction: 'Phase 1b: Supabase 연동',
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\personal-dashboard'],
    pinned: false,
    sort: 1,
    color: 'slate',
    updatedAt: NOW,
  },
  {
    id: 'p-brainct-fu',
    slug: 'brainct-fu',
    name: 'BrainCT_FU',
    group: 'research',
    subgroup: 'AI',
    status: 'active',
    summary: 'BrainCT 추적관찰 예측 연구',
    nextAction: '1차 평가지표 지도교수 논의',
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\Paper\\1.Writing\\BrainCT_FU'],
    pinned: false,
    sort: 0,
    color: 'emerald',
    updatedAt: NOW,
  },
  {
    id: 'p-deepvitalsignal',
    slug: 'deepvitalsignal',
    name: 'DeepVitalSignal',
    group: 'research',
    subgroup: 'AI',
    status: 'active',
    summary: '바이탈 시그널 딥러닝 연구',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\Paper\\1.Writing\\DeepVitalSignal'],
    pinned: false,
    sort: 1,
    color: 'teal',
    updatedAt: NOW,
  },
  {
    id: 'p-fre-nice-gformula',
    slug: 'fre-nice-gformula',
    name: '학위논문 FRE-NICE g-formula',
    group: 'research',
    subgroup: '역학',
    status: 'done',
    summary: '본심사 통과, 완료',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\Paper\\학위논문'],
    pinned: false,
    sort: 0,
    color: 'indigo',
    updatedAt: NOW,
  },
  {
    id: 'p-cxr2bc-tkr',
    slug: 'cxr2bc-tkr',
    name: 'CXR2BC_TKR',
    group: 'research',
    subgroup: '역학',
    status: 'active',
    summary: '57명 데이터 확인 필요',
    nextAction: '57명 데이터 확인',
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\Paper\\1.Writing\\CXR2BC_TKR'],
    pinned: false,
    sort: 1,
    color: 'fuchsia',
    updatedAt: NOW,
  },
  {
    id: 'p-ymc-mph',
    slug: 'ymc-mph',
    name: 'YMC_MPH',
    group: 'research',
    subgroup: '역학',
    status: 'active',
    summary: '',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\YMC_MPH'],
    pinned: false,
    sort: 2,
    color: 'lime',
    updatedAt: NOW,
  },
  {
    id: 'p-research-grant',
    slug: 'research-grant',
    name: '연구과제',
    group: 'research',
    subgroup: '개인연구',
    status: 'active',
    summary: '제안서/중간보고서 관리',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\연구과제'],
    pinned: false,
    sort: 0,
    color: 'orange',
    updatedAt: NOW,
  },
  {
    id: 'p-patents',
    slug: 'patents',
    name: '특허',
    group: 'research',
    subgroup: '개인연구',
    status: 'active',
    summary: 'CXR2BodyComposition, SimChest',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\Patent'],
    pinned: false,
    sort: 1,
    color: 'pink',
    updatedAt: NOW,
  },
  {
    id: 'p-fellowship',
    slug: 'fellowship',
    name: '펠로우 지원',
    group: 'personal',
    subgroup: '커리어',
    status: 'active',
    summary: '강남세브란스, Portfolio 준비',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Study\\Portfolio'],
    pinned: false,
    sort: 0,
    color: 'sky',
    updatedAt: NOW,
  },
  {
    id: 'p-obsidian-vault',
    slug: 'obsidian-vault',
    name: 'Obsidian vault',
    group: 'personal',
    subgroup: '공부',
    status: 'active',
    summary: '',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Documents\\kkd_obsidian'],
    pinned: false,
    sort: 0,
    color: 'stone',
    updatedAt: NOW,
  },
  {
    id: 'p-exam-priority',
    slug: 'exam-priority',
    name: '시험 우선순위',
    group: 'personal',
    subgroup: '공부',
    status: 'active',
    summary: '',
    nextAction: null,
    links: [],
    paths: ['/home/kkd2718/prio.json'],
    pinned: false,
    sort: 1,
    color: 'yellow',
    updatedAt: NOW,
  },
  {
    id: 'p-dating',
    slug: 'dating',
    name: '데이트 · 약속',
    group: 'personal',
    subgroup: '일상',
    status: 'active',
    summary: '',
    nextAction: null,
    links: [],
    paths: [],
    pinned: false,
    sort: 0,
    color: 'red',
    updatedAt: NOW,
  },
  {
    id: 'p-quant-lab',
    slug: 'quant-lab',
    name: 'quant-lab',
    group: 'app',
    subgroup: '재테크',
    status: 'archived',
    summary: 'Fable 세션이 만든 trading 게이트 실험, 결과 반영 완료',
    nextAction: null,
    links: [],
    paths: ['C:\\Users\\기덕\\Desktop\\Work\\quant-lab'],
    pinned: false,
    sort: 1,
    color: 'gray',
    updatedAt: NOW,
  },
];

const projectActivity: ProjectActivity[] = [];

const papers: Paper[] = [
  {
    id: 'paper-brainct-fu',
    title: 'BrainCT_FU',
    shortName: 'BrainCT_FU',
    stage: 'writing',
    track: 'AI',
    journal: null,
    manuscriptId: null,
    targetJournals: [],
    folderPath: null,
    nextAction: '1차 평가지표 지도교수 논의',
    projectId: 'p-brainct-fu',
    submissions: [],
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'paper-cxr2bc-tkr',
    title: 'CXR2BC_TKR',
    shortName: 'CXR2BC_TKR',
    stage: 'writing',
    track: '역학',
    journal: null,
    manuscriptId: null,
    targetJournals: ['JOA', 'KSRR', 'CiOS', 'KSSTA', 'BMC MSD'],
    folderPath: null,
    nextAction: '57명 데이터 확인',
    projectId: 'p-cxr2bc-tkr',
    submissions: [{ journal: 'OAC', submittedAt: null, decision: 'desk_reject', decidedAt: null }],
    sort: 1,
    updatedAt: NOW,
  },
  {
    id: 'paper-deepvitalsignal',
    title: 'DeepVitalSignal',
    shortName: 'DeepVitalSignal',
    stage: 'writing',
    track: 'AI',
    journal: null,
    manuscriptId: null,
    targetJournals: [],
    folderPath: null,
    nextAction: null,
    projectId: 'p-deepvitalsignal',
    submissions: [],
    sort: 2,
    updatedAt: NOW,
  },
  {
    id: 'paper-cxr2bodycomposition',
    title: 'CXR2BodyComposition',
    shortName: 'CXR2BodyComposition',
    stage: 'under_review',
    track: 'AI',
    journal: null,
    manuscriptId: null,
    targetJournals: [],
    folderPath: null,
    nextAction: null,
    projectId: 'p-patents',
    submissions: [],
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'paper-cxr2frailty',
    title: 'CXR2frailty',
    shortName: 'CXR2frailty',
    stage: 'revision',
    track: 'AI',
    journal: null,
    manuscriptId: null,
    targetJournals: [],
    folderPath: null,
    nextAction: null,
    projectId: null,
    submissions: [],
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'paper-dild',
    title: 'DILD',
    shortName: 'DILD',
    stage: 'revision',
    track: 'AI',
    journal: 'CMPB',
    manuscriptId: 'CMPB-S-22-00825',
    targetJournals: [],
    folderPath: null,
    nextAction: null,
    projectId: null,
    submissions: [],
    sort: 1,
    updatedAt: NOW,
  },
  {
    id: 'paper-knowledgeinjection-llm',
    title: 'KnowledgeInjection_LLM',
    shortName: 'KnowledgeInjection_LLM',
    stage: 'published',
    track: 'AI',
    journal: null,
    manuscriptId: null,
    targetJournals: [],
    folderPath: '3.Revision',
    nextAction: null,
    projectId: null,
    submissions: [],
    sort: 0,
    updatedAt: NOW,
  },
];

const reviews: ReviewJob[] = [];
const deadlines: Deadline[] = [];

const milestones: Milestone[] = [
  {
    id: 'ms-flow-sorter-pilot',
    projectId: 'p-flow-sorter',
    title: '실증 준비',
    startDate: null,
    endDate: null,
    status: 'active',
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'ms-realty-metro',
    projectId: 'p-realty-chart',
    title: '광역시 확장',
    startDate: null,
    endDate: null,
    status: 'planned',
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'ms-amgi-ingest',
    projectId: 'p-amgi',
    title: 'Neon 리셋 후 일괄 ingest',
    startDate: '2026-10-01',
    endDate: null,
    status: 'planned',
    sort: 0,
    updatedAt: NOW,
  },
  {
    id: 'ms-trading-ib-vr',
    projectId: 'p-trading-system',
    title: 'IB+VR 데몬 점검',
    startDate: null,
    endDate: null,
    status: 'active',
    sort: 0,
    updatedAt: NOW,
  },
];

const tasks: Task[] = [
  {
    id: 't-flow-local-ui',
    projectId: 'p-flow-sorter',
    milestoneId: 'ms-flow-sorter-pilot',
    title: '로컬 UI 검증',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-flow-deploy',
    projectId: 'p-flow-sorter',
    milestoneId: 'ms-flow-sorter-pilot',
    title: '배포 (Cloud Run + Vercel)',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-flow-bug-log',
    projectId: 'p-flow-sorter',
    milestoneId: 'ms-flow-sorter-pilot',
    title: '당일 버그 기록 양식 준비',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-flow-pilot-day',
    projectId: 'p-flow-sorter',
    milestoneId: 'ms-flow-sorter-pilot',
    title: '쉬는 날 하루 실사용',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 3,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-realty-metro-expand',
    projectId: 'p-realty-chart',
    milestoneId: 'ms-realty-metro',
    title: '광역시 확장 범위 정리',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-amgi-ingest',
    projectId: 'p-amgi',
    milestoneId: 'ms-amgi-ingest',
    title: 'R114~R168 일괄 ingest',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-trading-ib-vr',
    projectId: 'p-trading-system',
    milestoneId: 'ms-trading-ib-vr',
    title: 'IB+VR 실전 데몬 7/31 이후 미실행·주문 실패 2건 확인',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-cxr2bc-custodian',
    projectId: 'p-cxr2bc-tkr',
    milestoneId: null,
    title: '57명 데이터 custodian 확인',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-cxr2bc-joa',
    projectId: 'p-cxr2bc-tkr',
    milestoneId: null,
    title: 'JOA 투고 준비',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 't-brainct-supervisor',
    projectId: 'p-brainct-fu',
    milestoneId: null,
    title: '1차 평가지표 지도교수 논의',
    description: null,
    status: 'todo',
    dueDate: null,
    doneAt: null,
    sort: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

const notes: Note[] = [
  {
    id: 'note-example-1',
    body: '[예시] 메모에 아이디어를 빠르게 적어두세요. 나중에 할 일로 바꿀 수 있습니다.',
    kind: 'idea',
    status: 'inbox',
    projectId: null,
    tags: ['예시'],
    pinned: false,
    source: 'web',
    deliveredAt: null,
    taskId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'note-example-2',
    body: '[예시] 링크 공유도 여기로 모입니다. 모바일에서 공유 → Command Center 선택.',
    kind: 'link',
    status: 'inbox',
    projectId: null,
    tags: ['예시'],
    pinned: false,
    source: 'share',
    deliveredAt: null,
    taskId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'note-example-3',
    body: '[예시] 완료한 메모는 done 처리하거나 보관(archive)할 수 있습니다.',
    kind: 'memo',
    status: 'inbox',
    projectId: null,
    tags: ['예시'],
    pinned: false,
    source: 'web',
    deliveredAt: null,
    taskId: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'note-flow-sorter-pilot',
    body: 'flow-sorter 실증 — 쉬는 날 하루 클리닉 출근해서 실사용. 준비: 로컬 UI 검증, 배포(Cloud Run/Vercel), 당일 버그 기록 양식 → "실증 준비" 큐의 할 일로 전환됨',
    kind: 'todo',
    status: 'done',
    projectId: 'p-flow-sorter',
    tags: ['실증'],
    pinned: true,
    source: 'web',
    deliveredAt: null,
    taskId: 't-flow-local-ui',
    createdAt: NOW,
    updatedAt: NOW,
  },
];

/** Fresh copy of the seed database (deep-cloned, safe to mutate). */
export function seedDb(): Db {
  return JSON.parse(
    JSON.stringify({
      projects,
      projectActivity,
      papers,
      reviews,
      deadlines,
      notes,
      milestones,
      tasks,
    })
  ) as Db;
}
